import 'package:flutter/animation.dart';

class Appcolors{
  static Color maincolor=Color(0xff5B2ED4);
  static Color black2=Color(0xff344054);
  static Color onbmaintext=Color(0xff101828);
  static Color onbsubtext=Color(0xff475467);
  static Color signinicon=Color(0xff7A5AF8);
  static Color signinback=Color(0xff101321DE);
  static Color signinsuccesscontainer=Color(0xff795FFC);
   static Color signinsuccesssubcontainer=Color(0xffF95555);
  static Color entertext=Color(0xff98A2B3);
  static Color profcontainer=Color(0xffF4F6F9);
  static Color signin_color=Color(0xfffefefe);
  static Color white_color=Color(0xffffffff);
  static Color cream_color=Color(0xfff9fafb);
  static Color cream2_color=Color(0xffeaecf0);
  static Color black_color=Color(0xff000000);
  static Color red_color=Color(0xfff95555);
  static Color bgcolor=Color(0xffF4F4FA );
  static Color textfieldbg= Color(0xffF7F8FB);
  static Color outlinecolor= Color(0xff7A5AF8);
  static Color botomsheet= Color(0xffF9FAFB);
  static Color low_cream= Color(0xffe7e7e7);
  static Color gray = Color(0xff667085);
  static Color gray_light = Color(0xff475467);
  static Color low_white = Color(0xfffefefe);
  static Color smaallcont= Color(0xffD0D5DD);
  static Color proficoncolor= Color(0xff9B8AFB);
  static Color home_background =Color(0xff7155ff);
  static Color off_white =Color(0xfff9f9f9);
  static Color blac =Color(0xff161b23);
  static Color high_cream =Color(0xffcbecee);
  static Color yellow_light =Color(0xfff79009);
  static Color screens_background = Color(0xfff1f3f8);
  static Color green_light =Color(0xff19b36e);
  static Color orang_light =Color(0xfff95555);
  static Color choklet =Color(0xff2d2d2d);
  static Color gray_dark = Color(0xffB6C2D7);
}