import 'package:flutter/material.dart';

class Appicons{
  static const String email_icon='lib/assets/email_icon.png';
  static const String password_icon='lib/assets/password_icon.png';
  static const String close_eye_icon='lib/assets/close_eye_icon.png';
  static const String id_icon ='lib/assets/id_icon.png';
  static const String botombar_icon1='lib/assets/';
  static const String botombar_icon2='lib/assets/';
  static const String botombar_icon3='lib/assets/';
  static const String botombar_icon4='lib/assets/';
  // static const String botombar_icon5='lib/assets/';
  // static const String botombar_icon5='lib/assets/';
  static const String messenger_icon='lib/assets/meesenger_icon.png';
  static const String textbutton1='lib/assets/textbutton1.png';
  static const String textbutton='lib/assets/textbutton.png';
  static const String warning_icon='lib/assets/warning_icon.png';
  static const String profile_completion_icon='lib/assets/profile_completion_icon.png';
  static const String user_icon = 'lib/assets/user_icon.png';
  static const String assets_icon ='lib/assets/assets_icon.png';
  static const String tex_icon = 'lib/assets/tex_icon.png';
  static const String roles_icon = 'lib/assets/roles_icon.png';
  static const String settings_icon = 'lib/assets/setting_icon.png';
  static const String help_detail_icon = 'lib/assets/help_detail_icon.png';
  static const String vesion_icon = 'lib/assets/version_icon.png';
  static const String logout_icon = 'lib/assets/logout_icon.png';
   static const String user_icon1 ='lib/assets/user_icon.png';
   static const String date_of_birth_icon='lib/assets/date_of_birth_icon.png';
   static const String gender_selection_icon = 'lib/assets/gender_selection_icon.png';
   static const String clock_icon ='lib/assets/clock_icon.png';
   static const String to_do_icon ='lib/assets/to_do_icon.png';
    static const String workdone_icon ='lib/assets/work_done_icon.png';
    static const date_icon='lib/assets/date_icon.png';
    static const work_done_icon ='lib/assets/work_done_icon.png';
    static const location_icon ='lib/assets/location-tick.png';
    static const email_icon2 ='lib/assets/email_icon2.png';
     static const user_icon2 ='lib/assets/user_icon2.png';
     static const keyBoard = 'lib/assets/keyboard.png';
     static const location_icon2 ='lib/assets/location-icon2.png';
     static const profileframe_andicon='lib/assets/profile_frame_and_icon.png';
     static const assetsname_icon ='lib/assets/assetsname_icon.png';
     static const assetsbrand_icon ='lib/assets/assestbrand_icon.png';
     static const setting_icon2 = 'libs/assets/setting_icon3.png';
     static const buying_icon = 'lib/assets/buying_icon.png';
     static const payroll_icon ='lib/assets/payroll_icon.png';
     static const forgetpassword_mainIcon='lib/assets/forget_password_main_icon.png';
     static const forgetpassword_mainIcon2='lib/assets/forgetPassword_mainIcon.png';
}